// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package serialization is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Request
	ResponseMessages
	ResponseMembers
	ResponseProofs
*/
package serialization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_RequestType int32

const (
	Request_GetPendingMessages     Request_RequestType = 0
	Request_GetOrganizationMembers Request_RequestType = 1
	Request_GetProofsForMember     Request_RequestType = 2
)

var Request_RequestType_name = map[int32]string{
	0: "GetPendingMessages",
	1: "GetOrganizationMembers",
	2: "GetProofsForMember",
}
var Request_RequestType_value = map[string]int32{
	"GetPendingMessages":     0,
	"GetOrganizationMembers": 1,
	"GetProofsForMember":     2,
}

func (x Request_RequestType) String() string {
	return proto.EnumName(Request_RequestType_name, int32(x))
}
func (Request_RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Request struct {
	RequestType Request_RequestType `protobuf:"varint,1,opt,name=requestType,enum=serialization.Request_RequestType" json:"requestType,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetRequestType() Request_RequestType {
	if m != nil {
		return m.RequestType
	}
	return Request_GetPendingMessages
}

type ResponseMessages struct {
	Messages []*ResponseMessages_Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *ResponseMessages) Reset()                    { *m = ResponseMessages{} }
func (m *ResponseMessages) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessages) ProtoMessage()               {}
func (*ResponseMessages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseMessages) GetMessages() []*ResponseMessages_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ResponseMessages_Message struct {
	FromPublicKey string `protobuf:"bytes,1,opt,name=fromPublicKey" json:"fromPublicKey,omitempty"`
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *ResponseMessages_Message) Reset()                    { *m = ResponseMessages_Message{} }
func (m *ResponseMessages_Message) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessages_Message) ProtoMessage()               {}
func (*ResponseMessages_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ResponseMessages_Message) GetFromPublicKey() string {
	if m != nil {
		return m.FromPublicKey
	}
	return ""
}

func (m *ResponseMessages_Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ResponseMembers struct {
}

func (m *ResponseMembers) Reset()                    { *m = ResponseMembers{} }
func (m *ResponseMembers) String() string            { return proto.CompactTextString(m) }
func (*ResponseMembers) ProtoMessage()               {}
func (*ResponseMembers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ResponseProofs struct {
}

func (m *ResponseProofs) Reset()                    { *m = ResponseProofs{} }
func (m *ResponseProofs) String() string            { return proto.CompactTextString(m) }
func (*ResponseProofs) ProtoMessage()               {}
func (*ResponseProofs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Request)(nil), "serialization.Request")
	proto.RegisterType((*ResponseMessages)(nil), "serialization.ResponseMessages")
	proto.RegisterType((*ResponseMessages_Message)(nil), "serialization.ResponseMessages.Message")
	proto.RegisterType((*ResponseMembers)(nil), "serialization.ResponseMembers")
	proto.RegisterType((*ResponseProofs)(nil), "serialization.ResponseProofs")
	proto.RegisterEnum("serialization.Request_RequestType", Request_RequestType_name, Request_RequestType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x91, 0x08, 0x5c, 0x68, 0x30, 0x1e, 0xaa, 0xa8, 0x53, 0x64, 0x21, 0x91, 0x29,
	0x43, 0x79, 0x04, 0x10, 0x15, 0x42, 0x15, 0x95, 0xc5, 0xc2, 0x98, 0x94, 0x6b, 0x64, 0xa9, 0xb1,
	0x83, 0xed, 0x0e, 0xe5, 0x71, 0x18, 0x79, 0x4a, 0x44, 0x62, 0x43, 0xa2, 0x4e, 0x3e, 0xff, 0x77,
	0xdf, 0xf9, 0x7e, 0x1f, 0x24, 0x0d, 0x5a, 0x5b, 0xd6, 0x68, 0x8b, 0xd6, 0x68, 0xa7, 0xd9, 0xd4,
	0xa2, 0x91, 0xe5, 0x4e, 0x7e, 0x96, 0x4e, 0x6a, 0xc5, 0xbf, 0x09, 0x44, 0x02, 0x3f, 0xf6, 0x68,
	0x1d, 0x7b, 0x80, 0xd8, 0xf4, 0xe1, 0xeb, 0xa1, 0xc5, 0x94, 0x64, 0x24, 0x4f, 0x16, 0xbc, 0x18,
	0x01, 0x85, 0x2f, 0x0e, 0xe7, 0x6f, 0xa5, 0x18, 0x62, 0xfc, 0x0d, 0xe2, 0x41, 0x8e, 0xcd, 0x80,
	0x2d, 0xd1, 0xad, 0x51, 0xbd, 0x4b, 0x55, 0xaf, 0xfc, 0x2c, 0xf4, 0x84, 0xcd, 0x61, 0xb6, 0x44,
	0xf7, 0x62, 0xea, 0x52, 0xf9, 0xd6, 0x2b, 0x6c, 0x2a, 0x34, 0x96, 0x92, 0xc0, 0x18, 0xad, 0xb7,
	0xf6, 0x51, 0x9b, 0x3e, 0x41, 0x27, 0xfc, 0x8b, 0x00, 0x15, 0x68, 0x5b, 0xad, 0x2c, 0x86, 0x56,
	0xec, 0x1e, 0xce, 0x83, 0xc5, 0x94, 0x64, 0xa7, 0x79, 0xbc, 0xb8, 0x3d, 0x1a, 0x79, 0x8c, 0x14,
	0x3e, 0x10, 0x7f, 0xe0, 0xfc, 0x09, 0x22, 0x2f, 0xb2, 0x1b, 0x98, 0x6e, 0x8d, 0x6e, 0xd6, 0xfb,
	0x6a, 0x27, 0x37, 0xcf, 0x78, 0xe8, 0xfe, 0xe1, 0x42, 0x8c, 0x45, 0x96, 0x42, 0xb4, 0xd1, 0xca,
	0xa1, 0x72, 0xe9, 0x24, 0x23, 0xf9, 0xa5, 0x08, 0x57, 0x7e, 0x0d, 0x57, 0xff, 0x0f, 0x76, 0x8e,
	0x38, 0x85, 0x24, 0x48, 0xbd, 0xa9, 0xea, 0xac, 0x5b, 0xc6, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x49, 0x34, 0xe1, 0xab, 0x9e, 0x01, 0x00, 0x00,
}
